# Generated by Django 3.1.13 on 2021-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_auto_20211102_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='workDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Monthly Salary')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('insured', models.BooleanField(default=False, verbose_name='Company insured')),
                ('work_address', models.CharField(max_length=300, verbose_name='Work Address')),
            ],
        ),
    ]
