# Generated by Django 3.1.13 on 2021-11-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_workdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdetail',
            old_name='salary',
            new_name='gross_pay',
        ),
    ]
