# Generated by Django 3.1.13 on 2021-11-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0011_auto_20211124_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdetail',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='beneficiary_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='agentdetail',
            name='agend_ID',
            field=models.CharField(default='Agent-47E4813', max_length=100, verbose_name='Agent Id'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='agent_ID',
            field=models.ForeignKey(default='Agent-86668F1', on_delete=django.db.models.deletion.PROTECT, to='beneficiary.agentdetail'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_ID',
            field=models.UUIDField(default='Beneficiary-B95FF27', editable=False),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('facility_name', models.CharField(max_length=200, verbose_name='Facility Name')),
                ('department_name', models.CharField(choices=[('Dentistry', 'Dentistry'), ('Cardiology', 'Cardiology'), ('ENT Specialists', 'ENT Specialists'), ('Astrology', 'Astrology'), ('Neuroanatomy', 'Neuroanatomy'), ('Blood Screening', 'Blood Screening'), ('Eye Care', 'Eye Care'), ('Physical Therapy', 'Physical Therapy')], default='Dentistry', max_length=100, verbose_name='Department Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficiary.beneficiary')),
            ],
        ),
    ]
