# Generated by Django 3.1.13 on 2022-01-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0040_auto_20211231_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='service_facility',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='serviceproviderpersonel',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beneficiary.facility'),
        ),
    ]
