# Generated by Django 3.1.13 on 2022-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0044_auto_20220121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown')], max_length=100, null=True, verbose_name='HIV Status'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='supporting_documents'),
        ),
    ]
