# Generated by Django 2.2.21 on 2022-03-25 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('agent_id', models.CharField(editable=False, max_length=100)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('beneficiary_ids', models.CharField(editable=False, max_length=100)),
                ('art_status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_vl', models.IntegerField(blank=True, null=True)),
                ('hiv_status', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_spouse', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('number_of_siblings', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('alive', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Myplaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_comments', models.TextField(blank=True, null=True, verbose_name='Provider Comments')),
                ('interaction_date', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Prescription Comments')),
                ('no_of_days', models.IntegerField(blank=True, null=True, verbose_name='No of Days')),
                ('when_to_take', models.TextField(blank=True, max_length=500, null=True, verbose_name='When to Take')),
                ('lab', models.TextField(blank=True, null=True, verbose_name='Lab Comments')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplaces.Beneficiary')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='registered_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myplaces.Myplaces'),
        ),
    ]
